services:
  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - teamoop-network
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]
  database:
    image: postgres:12-alpine
    container_name: pg-db
    environment:
      - POSTGRES_DB=teamoopdb
      - POSTGRES_USER=teamoop
      - POSTGRES_PASSWORD=teamoop
    ports:
      - "1245:5432"

networks:
  teamoop-network:
