services:
  app-back:
    image: ghcr.io/lenelson/teamoop-backend:latest
    ports:
      - "8080:8080"
    networks:
      - teamoop-network
    environment:
      - SPRING_DATABASE_URL=${SPRING_DATABASE_URL}
      - SPRING_DATABASE_USERNAME=${SPRING_DATABASE_USERNAME}
      - SPRING_DATABASE_PASSWORD=${SPRING_DATABASE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - redis
      - pg-db
  pg-db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    networks:
      - teamoop-network
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${SPRING_REDIS_PASSWORD}"]

networks:
  teamoop-network:
