services:
  app-back:
    build:
      context: .
      target: dev
      dockerfile : ./Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://pg-db:5432/teamoopdb
      - SPRING_DATABASE_USERNAME=teamoop
      - SPRING_DATABASE_PASSWORD=teamoop
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - redis
      - pg-db
    networks:
      - teamoop-network
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  pg-db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=teamoopdb
      - POSTGRES_USER=teamoop
      - POSTGRES_PASSWORD=teamoop
    networks:
      - teamoop-network

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    networks:
      - teamoop-network
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]

networks:
  teamoop-network:
