url=jdbc:postgresql://localhost:1245/teamoopdb
username=teamoop
password=teamoop

driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog/master.xml
classpath=target/classes

referenceUrl=hibernate:spring:com.edj.teamoop.model?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver

contexts=dev,prod
logLevel=info
