
spring.datasource.url=jdbc:postgresql://localhost:1245/teamoopdb
spring.datasource.initialization-mode=always
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.enabled=true

logging.level.org.springframework.security=PROD
logging.level.org.springframework.web.cors=PROD
logging.level.org.springdoc=PROD