spring:
  application:
    name: teamoop
  security:
    enabled: false
  profiles:
    active: dev
  data:
    jpa:
      repositories:
        enabled: true

##Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

##CORS
cors:
  allowed:
    origin: http://localhost:4200

##logs
logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          redis=DEBUG:
        web:
          cors: DEBUG

      springdoc: DEBUG
