spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: username
    password: password
  cache:
    type: simple
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: false
    contexts: test
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  encryption:
    key: 5fd4d6432f2545ceb0078a3a992f31537c7c0fe65d31539d1bf403fb7bd0c596

  redis:
    host: localhost
    port: 6379
    password: password
    ttl:
      duration: 10m
