spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teamoopdb
    initialization-mode: none
    username: teamoop
    password: teamoop
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: false
    contexts: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
  encryption:
    key: 6de26826430254c3f53d73f3a046b1cd64869b8b73e15311227d9366ea220c49

  redis:
    host: localhost
    port: 6379
    password: password
    ttl:
      duration: 10m
  devtools:
    restart:
      enabled: true