spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: username
    password: password
  cache:
    type: simple
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: false
    contexts: test
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  encryption:
    key: 6de26826430254c3f53d73f3a046b1cd64869b8b73e15311227d9366ea220c49

  redis:
    host: localhost
    port: 6379
    password: password
    ttl:
      duration: 10m
