name: Build and Test Pipeline

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      
      # - name: Fail on direct push to main
      #   if: (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main') && github.event_name == 'push'
      #   run: |
      #     echo "Direct pushes to this branch are not allowed. Use pull requests instead."
      #     exit 1
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: mvn clean install --batch-mode --no-transfer-progress
