name: Docker Build and Push

on:
  workflow_run:
    workflows:
      - Build and Test Pipeline
    types:
      - completed
  pull_request:
    branches:
      - dev

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Debug workflow_run event
        run: |
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Event name: ${{ github.event_name }}"
          
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
        continue-on-error: true

      - name: Check artifact presence
        run: |
          if [ ! -f "app-jar" ]; then
            echo "Error: Artifact 'app-jar' not found!"
            exit 1
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define tags
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)
          DATE_TAG=$(date +"%Y%m%d%H%M")
          echo "IMAGE_TAG=v${DATE_TAG}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/edj/teamoop-backend:${{ env.IMAGE_TAG }} .
          docker tag ghcr.io/edj/teamoop-backend:${{ env.IMAGE_TAG }} ghcr.io/edj/teamoop-backend:latest
        continue-on-error: true
      
      - name: Verify Image Build
        run: |
          if ! docker image inspect ghcr.io/edj/teamoop-backend:${{ env.IMAGE_TAG }} > /dev/null 2>&1; then
            echo "Error: Docker image ghcr.io/edj/teamoop-backend:${{ env.IMAGE_TAG }} not built!"
            exit 1
          fi
      
      - name: Push Docker Image
        run: |
          docker push ghcr.io/edj/teamoop-backend:${{ env.IMAGE_TAG }}
          docker push ghcr.io/edj/teamoop-backend:latest

      - name: Clean up local Docker images
        run: |
          docker rmi ghcr.io/edj/teamoop-backend:${{ env.IMAGE_TAG }} || true
          docker rmi ghcr.io/edj/teamoop-backend:latest || true
