name: Code Coverage with JaCoCo

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build and Test with Coverage
        run: mvn clean verify jacoco:report --batch-mode --no-transfer-progress

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-html-report
          path: target/site/jacoco

      - name: Post JaCoCo Coverage in PR
        if: github.event_name == 'pull_request'
        run: |
          COVERED_LINES=$(grep -oP '(?<=<counter type="LINE" missed=")[^"]*' target/site/jacoco/jacoco.xml | awk '{missed += $1} END {print missed}')
          TOTAL_LINES=$(grep -oP '(?<=<counter type="LINE" covered=")[^"]*' target/site/jacoco/jacoco.xml | awk '{covered += $1} END {print covered}')
          PERCENT_COVERAGE=$((COVERED_LINES * 100 / (COVERED_LINES + TOTAL_LINES)))
          PERCENT_COVERAGE=$((COVERAGE * 100 / TOTAL_LINES))

          echo "**Nombre de lignes couvertes:** $COVERAGE/$TOTAL_LINES ($PERCENT_COVERAGE%)" >> coverage-summary.md

          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @- \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments <<EOF
          {
            "body": "$(cat coverage-summary.md)"
          }
